[data]
train_batch_size = 5000
test_batch_size = 5000

[model]
epochs = 10000
loss_threshold = 1
damping_factor = 0.7
epsilon = 0.00000001
learning_rate = 0.00005
skip_profiling = 1
default_focus_iteration_neg_offset = 1
default_focus_iteration_pos_offset = 1

[device]
device = "mps"
