[device]
device = "cuda:0"

[model]
hidden_sizes = [500, 500, 500, 500, 500]
epochs = 30000
prelabel_timesteps = 2
loss_threshold = 1.5
damping_factor = 0.7
epsilon = 0.00000001
skip_profiling = 1
ff_activation = "relu"
ff_optimizer = "rmsprop"
classifier_optimizer = "adam"
should_log_metrics = true 
should_replace_neg_data = false
should_load_weights = false
lr_step_size = 10000
lr_gamma = 0.90
dropout = 0.0

[model.connection_profile]
forward_block_sizes = [20, 20, 20, 20, 20, 20]
backward_block_sizes = [50, 50, 50, 50, 50, 50]
lateral_block_sizes = [100, 100, 100, 100, 100, 100]
forward_block_bleed = [0.1, 0.15, 0.2, 0.25, 0.3, 0.35]
backward_block_bleed = [0.1, 0.15, 0.2, 0.3, 0.4, 0.5]
lateral_block_bleed = [0.15, 0.2, 0.3, 0.35, 0.45, 0.5]

[model.ff_rmsprop]
momentum = 0.0
learning_rate = 0.00005

[model.classifier_rmsprop]
momentum = 0
learning_rate = 0.00001

[model.ff_adam]
learning_rate = 0.00001

[model.classifier_adam]
learning_rate = 0.01

[model.ff_adadelta]
learning_rate = 0.0001

[model.classifier_adadelta]
learning_rate = 0.00001
