[device]
device = "cuda"

[model]
hidden_sizes = [200, 200, 200]
epochs = 30000
loss_threshold = 1.5
damping_factor = 0.7
epsilon = 0.00000001
skip_profiling = 1
should_log_metrics = true 
should_replace_neg_data = false
ff_activation = "relu"
ff_optimizer = "rmsprop"
classifier_optimizer = "adam"
interconnect_density = 1

[model.ff_rmsprop]
momentum = 0.4
learning_rate = 0.000005

[model.classifier_rmsprop]
momentum = 0
learning_rate = 0.00001

[model.ff_adam]
learning_rate = 0.00001

[model.classifier_adam]
learning_rate = 0.01

[model.ff_adadelta]
learning_rate = 0.0001

[model.classifier_adadelta]
learning_rate = 0.00001
