[model]
hidden_sizes = [2000, 2000, 2000]
epochs = 10000
loss_threshold = 1
damping_factor = 0.7
epsilon = 0.00000001
learning_rate = 0.00001
skip_profiling = 1
should_log_metrics = true 
should_replace_neg_data = true
learning_momentum = 0.25
classifier_learning_momentum = 0

[device]
device = "mps"

