[model]
hidden_sizes = [3000, 3000, 3000]
epochs = 275
loss_threshold = 1
damping_factor = 0.7
epsilon = 0.00000001
skip_profiling = 1
should_log_metrics = true 
should_replace_neg_data = true
ff_activation = "relu"
ff_optimizer = "rmsprop"
classifier_optimizer = "adadelta"
convolutions_enabled = true

[model.convolutions]
output_channels = 16

[model.ff_rmsprop]
momentum = 0.2
learning_rate = 0.00001

[model.classifier_rmsprop]
momentum = 0
learning_rate = 0.01

[model.ff_adam]
learning_rate = 0.00001

[model.classifier_adam]
learning_rate = 0.001

[model.ff_adadelta]
learning_rate = 0.0001

[model.classifier_adadelta]
learning_rate = 0.00001

[device]
device = "mps"

