program: new_search.py
method: bayes
metric:
  goal: maximize
  name: train_accuracy
parameters:
  learning_rate:
    min: 0.0000005
    max: 0.0005
  momentum:
    min: 0.0
    max: 1.0
  prelabel_timesteps:
    min: 3
    max: 10
  iterations:
    min: 10
    max: 20
  loss_scale_ff:
    min: 0.0
    max: 1.0
  loss_scale_predictive:
    min: 0.0
    max: 1.0
  loss_scale_hebbian:
    min: 0.0
    max: 1.0
  loss_scale_decorrelative:
    min: 0.0
    max: 1.0
  damping_factor:
    min: 0.1
    max: 0.9