name: CI

on:
  push:
    branches:
      - main
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: self-hosted
    timeout-minutes: 360
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/pip/requirements.txt

    # TODO: fix this when worker agent stabilized
    # - name: Run CI test
    #   run: ./test/scripts/ci.sh