name: Python PEP 8 compliance check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run PEP 8 compliance check
      run: ./test/scripts/pep8.sh