name: "Smoke Test Benchmarks"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/pip/requirements.txt

      - name: Validate commands
        run: ./test/scripts/smoke.sh